import os

SHEET_URL = os.getenv("VECTRA_GOOGLE_SHEET_URL")
LOW_VOLUME_THRESHOLD = float(os.getenv("VECTRA_LOW_VOLUME_THRESHOLD", "1"))
EMPTY_SKU_LABEL = os.getenv("VECTRA_EMPTY_SKU_LABEL", "Без SKU")


# Decision Engine v1 assumptions (configurable, temporary)
DECISION_LOGISTICS_COEF = float(os.getenv("VECTRA_DECISION_LOGISTICS_COEF", "0.7"))
DECISION_PERSONNEL_COEF = float(os.getenv("VECTRA_DECISION_PERSONNEL_COEF", "0.5"))
DECISION_RETRO_COEF = float(os.getenv("VECTRA_DECISION_RETRO_COEF", "0.6"))
DECISION_OTHER_COEF = float(os.getenv("VECTRA_DECISION_OTHER_COEF", "0.4"))
DECISION_MIN_EFFECT_ABS = float(os.getenv("VECTRA_DECISION_MIN_EFFECT_ABS", "10000"))
DECISION_MIN_EFFECT_SHARE = float(os.getenv("VECTRA_DECISION_MIN_EFFECT_SHARE", "0.02"))
AI_FOCUS_SHARE_THRESHOLD = float(os.getenv("VECTRA_AI_FOCUS_SHARE_THRESHOLD", "0.60"))
DRAIN_SHARE_THRESHOLD = float(os.getenv("VECTRA_DRAIN_SHARE_THRESHOLD", "0.80"))
DRAIN_MIN_ITEMS = int(os.getenv("VECTRA_DRAIN_MIN_ITEMS", "3"))
DRAIN_MAX_ITEMS = int(os.getenv("VECTRA_DRAIN_MAX_ITEMS", "7"))
